<a href="https://colab.research.google.com/github/trembalamg/ExtensaoPythonPandas/blob/main/PrimeiroExemploEmPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Primeiro exemplo de manipulação de dados usando Python Pandas**

Autor: Caio Sousa

Data: 06/02/2023

In [4]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [5]:
#Importando biblioteca pandas no Python
import pandas as pd

combustiveis_df = pd.read_excel("ca-2021-02.xlsx")

In [6]:
#Usa o print para ver o dataframe!
print (combustiveis_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [7]:
#display() mostra muito mais organizado e bonito!
display (combustiveis_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [8]:
#Exibe as primeiras 5 linhas
print (combustiveis_df.head())

  Regiao - Sigla Estado - Sigla  Municipio               Revenda  \
0             NE             AL  ARAPIRACA  POSTO ARAPIRACA LTDA
1             NE             AL  ARAPIRACA  POSTO ARAPIRACA LTDA
2             NE             AL  ARAPIRACA  POSTO ARAPIRACA LTDA
3             NE             AL  ARAPIRACA  POSTO ARAPIRACA LTDA
4             NE             AL  ARAPIRACA  POSTO ARAPIRACA LTDA

       CNPJ da Revenda     Nome da Rua Numero Rua Complemento       Bairro  \
0   12.451.076/0004-65  RODOVIA AL 220        105       KM 68  CANAFISTULA
1   12.451.076/0004-65  RODOVIA AL 220        105       KM 68  CANAFISTULA
2   12.451.076/0004-65  RODOVIA AL 220        105       KM 68  CANAFISTULA
3   12.451.076/0004-65  RODOVIA AL 220        105       KM 68  CANAFISTULA
4   12.451.076/0004-65  RODOVIA AL 220        105       KM 68  CANAFISTULA

         Cep             Produto Data da Coleta  Valor de Venda  \
0  57302-605            GASOLINA     2021-11-01           6.799
1  57302-605              ETANOL     2021-11-01           5.299
2  57302-605              DIESEL     2021-11-01           5.549
3  57302-605  GASOLINA ADITIVADA     2021-11-01           6.899
4  57302-605          DIESEL S10     2021-11-01           5.649

   Valor de Compra Unidade de Medida       Bandeira
0              NaN        R$ / litro  VIBRA ENERGIA
1              NaN        R$ / litro  VIBRA ENERGIA
2              NaN        R$ / litro  VIBRA ENERGIA
3              NaN        R$ / litro  VIBRA ENERGIA
4              NaN        R$ / litro  VIBRA ENERGIA

In [9]:
display (combustiveis_df.head())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA

In [10]:
#Quero, na verdade, exibir as primeiras 15 linhas
display (combustiveis_df.head(15))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.987,NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.978,NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.989,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA

In [11]:
#Comandos Dataframe.shape e Dataframe.describe()
print (combustiveis_df.shape)
#mostra o numero de linhas e colunas (linhas, colunas)
#só as linhas
print ("\n#############################\n")
print(combustiveis_df.shape[0])
#só as colunas
print ("\n#############################\n")
print(combustiveis_df.shape[1])
print ("\n#############################\n")

(168409, 16)

#############################

168409

#############################

16

#############################

In [12]:
#Quais são as colunas e que tipo de dados cada uma tem
print (combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [13]:
#Describe() mostra as estatísticas mais básicas que a gente precisa
print (combustiveis_df.describe())

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [15]:
#filtrar apenas por uma coluna
display(combustiveis_df['Revenda'])

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [16]:
#Aqui criamos um novo dataframe apenas com as colunas que eu quero...
ca_df = combustiveis_df[['Revenda', 'Municipio','Produto', 'Valor de Venda','Estado - Sigla']]
print(ca_df)

                                           Revenda  Municipio  \
0                             POSTO ARAPIRACA LTDA  ARAPIRACA
1                             POSTO ARAPIRACA LTDA  ARAPIRACA
2                             POSTO ARAPIRACA LTDA  ARAPIRACA
3                             POSTO ARAPIRACA LTDA  ARAPIRACA
4                             POSTO ARAPIRACA LTDA  ARAPIRACA
...                                            ...        ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA     JEQUIE
168405           ABC DISTRIBUICAO DE PETROLEO LTDA  ITUIUTABA
168406           ABC DISTRIBUICAO DE PETROLEO LTDA  ITUIUTABA
168407           ABC DISTRIBUICAO DE PETROLEO LTDA  ITUIUTABA
168408           ABC DISTRIBUICAO DE PETROLEO LTDA  ITUIUTABA

                   Produto  Valor de Venda Estado - Sigla
0                 GASOLINA           6.799             AL
1                   ETANOL           5.299             AL
2                   DIESEL           5.549             AL
3       GASOLINA ADITIVADA           6.899             AL
4               DIESEL S10           5.649             AL
...                    ...             ...            ...
168404              ETANOL           5.859             BA
168405            GASOLINA           6.580             MG
168406              ETANOL           4.740             MG
168407          DIESEL S10           5.448             MG
168408  GASOLINA ADITIVADA           6.580             MG

[168409 rows x 5 columns]

In [17]:
#Exibe a 4a. linhas
display(ca_df.loc[3])

Revenda           POSTO ARAPIRACA LTDA
Municipio                    ARAPIRACA
Produto             GASOLINA ADITIVADA
Valor de Venda                   6.899
Estado - Sigla                      AL
Name: 3, dtype: object

In [18]:
#Exibir da 10a. Linha até a 20a. linhas
display(ca_df.loc[9:19])

,Revenda,Municipio,Produto,Valor de Venda,Estado - Sigla
9,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.983,AL
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197,AL
11,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,ETANOL,5.987,AL
12,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL,5.978,AL
13,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.989,AL
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA,7.175,AL
15,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,ETANOL,5.930,AL
16,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,DIESEL,5.955,AL
17,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA ADITIVADA,7.175,AL
18,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.980,AL
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,GASOLINA,6.990,AM

In [20]:
#Criar uma dataframe gas_df contendo apenas as 4 colunas (Revenda, Municipio, Produto, Valor de Venda) somente com combustível sendo GASOLINA
gas_df = ca_df.loc[ca_df['Produto'] == 'GASOLINA']
display(gas_df)
display(gas_df['Valor de Venda'].max())

,Revenda,Municipio,Produto,Valor de Venda,Estado - Sigla
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799,AL
5,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,GASOLINA,7.198,AL
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197,AL
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA,7.175,AL
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,GASOLINA,6.990,AM
...,...,...,...,...,...
168392,AUTO POSTO KM BAURU LTDA,BAURU,GASOLINA,6.199,SP
168394,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,ITUIUTABA,GASOLINA,6.899,MG
168399,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,CAMPOS DOS GOYTACAZES,GASOLINA,7.090,RJ
168403,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,GASOLINA,6.799,BA
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580,MG

7.999

In [21]:
#Se eu quiser saber qual é o posto e município da gasolina mais cara do país?
display(gas_df[['Revenda','Municipio','Estado - Sigla', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Estado - Sigla                           TO
Valor de Venda                        7.999
dtype: object

In [83]:
#DataFrame.loc[] com múltiplas condições para filtragem
#Quais são os preços, postos que vendem ETANOL na minha cidade (INDAIATUBA) 
#ordenado do menor valor de venda para o maior
etanol_indaiatuba_df = ca_df.loc[(ca_df['Produto'] == 'ETANOL') & (ca_df['Municipio'] == 'INDAIATUBA')]
display(etanol_indaiatuba_df.sort_values(by='Valor de Venda'))

,Revenda,Municipio,Produto,Valor de Venda,Estado - Sigla
160592,AUTO POSTO NAMORADA II LTDA.,INDAIATUBA,ETANOL,4.679,SP
140194,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,INDAIATUBA,ETANOL,4.679,SP
140661,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,INDAIATUBA,ETANOL,4.699,SP
159497,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,INDAIATUBA,ETANOL,4.699,SP
141167,AUTO POSTO ESPLANADA DE INDAIA LTDA,INDAIATUBA,ETANOL,4.699,SP
...,...,...,...,...,...
51129,AUTO POSTO CIDADE DO SOL II LTDA,INDAIATUBA,ETANOL,5.599,SP
51138,AUTO POSTO NAMORADA II LTDA.,INDAIATUBA,ETANOL,5.599,SP
84395,AUTO POSTO NAMORADA II LTDA.,INDAIATUBA,ETANOL,5.599,SP
65878,AUTO POSTO CIDADE DO SOL II LTDA,INDAIATUBA,ETANOL,5.599,SP
65363,AUTO POSTO INDIANA SELF LTDA.,INDAIATUBA,ETANOL,6.197,SP

In [72]:
# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & (combustiveis_df['Municipio'] == 'SAO PAULO') & ((combustiveis_df['Produto'] == 'GASOLINA') | (combustiveis_df['Produto'] == 'GASOLINA ADITIVADA')), ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [73]:
# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & (combustiveis_df['Municipio'] == 'SAO PAULO') & (combustiveis_df['Produto'].isin(["GASOLINA", "GASOLINA ADITIVADA"])), ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [70]:
#Como mostrar média de valor de venda POR COMBUSTÍVEL Brasil todo?
media_por_combustivel_df = ca_df[['Produto', 'Valor de Venda']].groupby(by='Produto').mean().round(2)
display(media_por_combustivel_df)

                    Valor de Venda
Produto
DIESEL                        5.38
DIESEL S10                    5.45
ETANOL                        5.46
GASOLINA                      6.71
GASOLINA ADITIVADA            6.86
GNV                           4.39

In [75]:
#Quero adicionar uma coluna de valor booleano no combustiveis_df chamada "Ativo" que, por padrão, vai ser True para todas as linhas
combustiveis_df['Ativo'] = True
print(combustiveis_df.info())
display(combustiveis_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True

In [77]:
#E se eu quiser uma coluna nova chamada "Obs" que preencha automaticamente "MELHOR CIDADE" quando o Município for INDAIATUBA, SP...
#combustiveis_df['Obs'] = "MELHOR CIDADE" if combustiveis_df['Municipio'] == "INDAIATUBA" else ""

In [85]:
# Exportar para Excel o dataframe com etanol em Indaiatuba....
etanol_indaiatuba_df.to_excel('etanol_indaiatuba.xlsx', sheet_name='Etanol em Indaiatuba')